title: Code for Africa
description: > # Description
  Code for Africa (CfAfrica) is Africa’s largest data journalism and civic technology initiative, operating CitizenLabs across the continent to help fast-track digital experimentation and transformation in newsrooms and other social justice organisations.

baseurl:

url: https://codeforafrica.org   # with the https protocol
enforce_ssl: codeforafrica.org   # without any protocol
